### ISSUE TITLE
/var/local/ucs/clean.ucs: FAILED open or read

### ISSUE THREAD

**Issue by Mikawamoto** [f5devcentral/f5-aws-migrate#1]
In the following steps during script execution, the following error occurred. What is the cause?

RUNNING cmd: run util bash -c 'md5sum -c /var/local/ucs/clean.ucs.md5'
Password:
md5sum: /var/local/ucs/clean.ucs: No such file or directory
md5sum: WARNING: 1 of 1 listed file could not be read
cmd_output:
/var/local/ucs/clean.ucs: FAILED open or read

**Comment by kskoh** [comment]
@Mikawamoto  Seems like the ucs saved on the old instance was not scp over to the new instance.  Can you check the content of dir /var/local/ucs?  What do we have in there?

Provide the full command line you ran with. What is your scenario in using this script per the following 4 available scenarios?

1. Utility to Utility (Do not need registration key)
2. Utility to BYOL (Must have new BYOL registration key)
3. BYOL to BYOL (Must contact F5 Support to request an Allow Move on registration key)
4. BYOL to Utility (Do not need registration key)

**Comment by Mikawamoto** [comment]
Thanks,
There's nothing in /var/local.
There is There is "f5-[indtance ID]-clean.ucs" in /home/ec2-user, but not "clean.ucs" anywhere.
My scenario is "1. Utility to Utility (Do not need registration key)" and I ran with the following command.
$ python f5-aws-migrate.py -C -k /home/john/.ssh/VE-DEMO.pem -i i-e0880167 -m 10.0.0.245 -u admin -p ‘strongpassword’ -d ami-d9ee1ab9 -R us-west-2 --debug-level 1

**Comment by Mikawamoto** [comment]
It seems that this error appears when scp being failed for sending "clean.ucs" during the execution of the script. It succeeds unless scp is failed. I don't know why scp fails. If it is not in CVE mode, it will not fail scp sending.
