### ISSUE TITLE
difference of script log of normal mode and CVE mode

### ISSUE THREAD

**Issue by Mikawamoto** [f5devcentral/f5-aws-migrate#2]
I ran f5-aws-migrate.py with normal mode, end of script log is following;
Waiting 30 seconds for mcpd to restart...Please wait...
RUNNING cmd: save /sys ucs /var/tmp/f5-pre-restore-i-xxxx.ucs
Password:
cmd_output:
Saving active configuration...
/var/tmp/f5-pre-restore-i-xxxx.ucs is saved.

Uploading file: f5-i-xxxx.ucs to host: 172.31.x.x
Password:
scp_output:
None
Uploading file: f5-i-xxxx.ucs.md5 to host: 172.31.x.x
Password:
scp_output:
None
RUNNING cmd: run util bash -c 'md5sum -c /var/local/ucs/f5-i-xxxx.ucs.md5'
Password:
cmd_output:
/var/local/ucs/f5-i-xxxx.ucs: OK

RUNNING cmd: run util bash -c 'tmsh load sys ucs /var/local/ucs/f5-i-xxxx.ucs no-license'
Password:
Extracting manifest: /var/local/ucs/f5-i-xxxx.ucs
Product : BIG-IP
Platform: Z100
Version : 14.0.0.1
Edition : Point Release 1
Hostname: ip-172-31-x-x.us-west-1.compute.internal
Installing --full-- configuration on host ip-172-31-x-x.us-west-1.compute.internal
Installing configuration...
<131>Sep 17 23:00:26 ip-172-31-x-x loaddb[19315]: 01080023:3: Error return while getting reply from mcpd: 0x107178a, 0107178a:3: Modifying license.maxcores to a value other than 8 is not allowed.
Error 0x107178a occurred: 0107178a:3: Modifying license.maxcores to a value other than 8 is not allowed.
Post-processing...
usermod: no changes
Reloading License and configuration - this may take a few minutes...
Configuration loading error: base-config-load-failed
For additional details, please see messages in /var/log/ltm

WARNING: There were one or more errors detected during installation.
        Check the error messages and take the proper actions if needed.
ERROR: UCS installation failed.
Operation aborted.
Unexpected Error: UCS loading process failed.
cmd_output:
Processing UCS file: /var/local/ucs/f5-i-xxxx.ucs

Installing full UCS (14.0.0.1) data, excluding license file.

_____BIG-IP Migration Completed_____

But, end of script log of CVE mode was as such;
Waiting 30 seconds for mcpd to restart...Please wait...
Uploading file: f5-i-xxxx-clean.ucs to host: 172.31.x.x
Password:
scp_output:
None
Uploading file: f5-i-xxxx-clean.ucs.md5 to host: 172.31.x.x
Password:
scp_output:
None
RUNNING cmd: run util bash -c 'md5sum -c /var/local/ucs/clean.ucs.md5'
Password:
cmd_output:
/var/local/ucs/clean.ucs: OK

Uploading file: restore-clean-ucs to host: 172.31.x.x
Password:
scp_output:
None
Masterkey from file = M(Wj8'%R$Exw
SSH'ing to : admin@172.31.x.x
Traceback (most recent call last):
 File "f5-aws-migrate.py", line 1092, in <module>
   main()
 File "f5-aws-migrate.py", line 1032, in main
   pexpect_restore_clean_ucs ( username, ssh_key, password, management_ip, masterkey1, debug_level )
 File "f5-aws-migrate.py", line 128, in pexpect_restore_clean_ucs
   match_value = conn.expect('\(tmos\)#', timeout=MY_TIMEOUT)
 File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 341, in expect
   timeout, searchwindowsize, async_)
 File "/usr/lib/python2.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
   return exp.expect_loop(timeout)
 File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 119, in expect_loop
   return self.timeout(e)
 File "/usr/lib/python2.7/site-packages/pexpect/expect.py", line 82, in timeout
   raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f1cc2ddcd10>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-i', '/home/ec2-user/.ssh/xxxx.pem', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'admin@172.31.x.x']
buffer (last 100 chars): 'y will be ignored.\r\r\nLoad key "/home/ec2-user/.ssh/xxxx.pem": bad permissions\r\r\nPassword: '
before (last 100 chars): 'y will be ignored.\r\r\nLoad key "/home/ec2-user/.ssh/xxxx.pem": bad permissions\r\r\nPassword: '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 19795
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
   0: re.compile('\\(tmos\\)#')

why ? I'm afraid if CVE mode finished unnormaly.

**Comment by kskoh** [comment]
What version is the source BIG-IP that is migrated to BIG-IP v14.0.0.1 in this scenario?  I have not tested this script with BIG-IP v14.x so there might be bug(s).  I will test it out at the end of this week.  Let you know sometime next week about my findings.

**Comment by Mikawamoto** [comment]
Thanks,
the version of source BIG-IP is 14.0.0.1-0.0.2.
I want to migrate from AWS AMI "F5 BIG-IP Virtual Edition - BEST (PAYG, 25Mbps)" to "F5 BIG-IP Virtual Edition - BEST (PAYG, 200Mbps)".

**Comment by kskoh** [comment]
Hi @Mikawamoto, an update for you. My side tested the migrate script against the current images available on AWS Marketplace and we are not successful. We tested with v12, v13 and v14 images and running into a few issues.  One issue we resolved in the script is due to the image name for payg was used to be called hourly in the ami name.  Now it is called payg so we change the script to reflect that.  Other issues we have not resolved is UCS load failures with these new images.  We have to do more research and testing in our team to further support this script.

**Comment by Mikawamoto** [comment]
Thank you for everything. 
How long will it take to research and test?

**Comment by Mikawamoto** [comment]
Hi,
I would like to know the current status.

**Comment by adam-f5** [comment]
Repository Archived
